<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Visitor</AssemblyName>
    <RootNamespace>Patrones.Comportamiento.Visitor</RootNamespace>
  </PropertyGroup>
</Project>
