<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Composite</AssemblyName>
    <RootNamespace>Patrones.Estructurales.Composite</RootNamespace>
  </PropertyGroup>
</Project>
